package com.launchpath.ai_service.dto.request;


import com.launchpath.ai_service.enums.ExperienceLevel;
import lombok.Getter;
import lombok.Setter;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;

import java.util.List;

@Getter
@Setter
public class AnalyzeCareerRequestDTO {

    @NotBlank(message = "userId is required")
    private String userId;

    @NotBlank(message = "targetRole is required")
    private String targetRole;

    @NotNull(message = "experienceLevel is required")
    private ExperienceLevel experienceLevel;

    // Current skills user has
    private List<String> skills;

    // SHA-256 hash of resume — for cache check
    // Generated by resume-service before calling
    private String resumeHash;

    // Structured resume data
    private ResumeDataDTO resumeData;

    @Getter
    @Setter
    public static class ResumeDataDTO {
        private List<String> projects;
        private List<String> experience;
        private List<String> education;
        private List<String> certifications;
    }
}
